name: Digital Ocean Deployment

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@1.2.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME  }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/WWw/portfolio
            git pull origin main
            npm ci
            npm run build
            pm2 reload portfo-test
            pm2 save
